// react-train-ticket/src/App.js
/*
 * @Author: your name
 * @Date: 2019-08-20 14:08:08
 * @LastEditTime : 2020-01-17 10:21:28
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \react-train-ticket\src\App.js
 */
import React from 'react';

import './App.css';
import Learn from './learn/learn.js';
import Todo from './learn/todo.js';

function App () {
  return (
    <div>
      <Learn/>
      <Todo/>
    </div>
  )
}

export default App;

// typeScript-learn/vue-ts-app/src/App.vue
<!--
 * @Author: your name
 * @Date: 2020-02-22 23:16:55
 * @LastEditTime: 2020-02-24 12:17:19
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \vue-ts-app\src\App.vue
 -->
<template>
  <section class="todoapp">
    <Header @submit="addTodo" />
    <Main :todos="filteredTodos"></Main>
    <Footer></Footer>
    <Button size="100x20"/>
  </section>
</template>

<script lang="ts">
// interface Todo {
//   text: string
//   completed: boolean
// }
// 注意是三个反斜线，但是这个已经被淘汰了
// /// <reference path="./components/types.d.ts"/>
import { Vue, Component } from 'vue-property-decorator'
import Header from './components/Header.vue'
import Main from './components/Main.vue'
import Footer from './components/Footer.vue'
import Button from './components/Button.vue';
// eslint-disable-next-line no-unused-vars
import { Todo } from './types'

// 能在class内部实现的特性都在内部使用,不能在内部实现的都用components装饰器的参数传递
  @Component({
    components: {
      Header,
      Main,
      Footer,
      Button
    }
  })
  export default class App extends Vue {
    private todos: Todo[]
    constructor () {
      super()
      this.todos = [
        {text: 'aa',completed: false},
        {text: 'bbb',completed: false}
      ]
    }
    // 计算属性
    get filteredTodos () {
      return this.todos.filter(t => t.completed)
    }
    addTodo (text: string) {
      // console.log(text)
      this.todos.push({ text, completed: false })
    }

  }
</script>
